### PR TITLE
feat(typings): add initial typings

### LINKED ISSUE #18: Add Typescript Typings

### PR DESCRIPTION
**Pull request by MeirionHughes**
closes #18

### CODE REVIEW

**Comment by ralphtheninja** [comment]
@MeirionHughes I accidentally merged the `abstract-leveldown@2.7.0`-PR so just gonna cherry pick your latest commit from this PR.

**Comment by ralphtheninja** [comment]
4171664

**Comment by hoegge** [comment]
Dear @ralphtheninja - were these typings never merged with the released version?

**Comment by vweevers** [comment]
@hoegge typings are maintained in DT now.

**Comment by hoegge** [comment]
Thanks @vweevers - I confused `rocksdb` with `level-rocksdb` - there is no typings for that?

**Pull request closed without merging**
