### PR TITLE
Move RocksDB to git submodule

### LINKED ISSUE #140: RocksDB version upgrade
Hi, I'm trying to upgrade RocksDB version used in this package:

1. I've downloaded latest release from RocksDB official github, replaced the contents of /deps/leveldb/leveldb-rocksdb with it.

2. Updated the leveldb.gyp to [this](https://github.com/lu4/rocksdb-ts/blob/be498e93c54c34a64e0d888f61539d229eab6576/deps/leveldb/leveldb.gyp) content which can be also found in [this diff](https://github.com/lu4/rocksdb-ts/commit/be498e93c54c34a64e0d888f61539d229eab6576#diff-fe74db22d3e05f3e0fb5effc5b4df636) and the whole fork can be [found here](https://github.com/lu4/rocksdb-ts).

(I've also temporarily removed some of the code to pinpoint the issue, please ignore those changes)

Now when I install the package locally the compilation phase goes smooth, package installs successfully but when I try to run the code through requiring the package I get runtime error

Error image

Any thoughts on how to deal with this issue?

### PR DESCRIPTION
**Pull request by vweevers**
Forked from #82. Closes #140.

I've yet to review it myself. I only rebased it, and removed the hardcoded sha1 for `build_version.cc`, which I know we will forget to update at some point - so I prefer not having it.

### CODE REVIEW

**Comment by lu4** [comment]
Yes, I've been just doing manual comparison of projects and it turned out that snappy libs are identical, so I thought that actual rebase could have helped

**Comment by lu4** [comment]
Lemme see the difference between this PR and thing I have on my local machine just in case check if nothing was missed...

**Comment by lu4** [comment]
Ok, here are the changes we've discussed in #140 thread

**Comment by vweevers** [comment]
Remaining tasks:

- [ ] Review (in progress)
- [ ] Merge https://github.com/Level/rocksdb/pull/142
- [ ] Upgrade to at least https://github.com/facebook/rocksdb/commit/3b4d1b7a446dcf7cc6937db4f61734f7b0093a09 to avoid a regression of https://github.com/Level/rocksdb/pull/86
- [ ] Check `.gitignore` and `.npmignore` (we made some changes there, make sure paths still match)
- [ ] Test compiling inside npm package (without git metadata being available)

**Comment by lu4** [comment]
@vweevers I've also noticed there's a high severity vulnerability found in `dependency-check`, it'll be good to probably upgrade dependencies?

**Comment by vweevers** [comment]
That's only a devDependency so hasn't got me worried. That said, upgrading should be easy (#128)

**Comment by vweevers** [comment]
@lu4 How's it going with the RocksDB upgrade? Do you wanna take it from here?

**Comment by lu4** [comment]
@vweevers I'm doing final check

**Comment by vweevers** [comment]
> 10 minutes to rebuild then 10 minutes to install

Are you using `npm run rebuild` to rebuild? That should be the only step needed.

**Comment by lu4** [comment]
@vweevers Yes, I first do `npm run rebuild` then I go to my test project, and do `npm uninstall rocksdb-ts && npm i ../rocksdb-ts`, then I try to run it. The thing is that the issue I'm seeing is runtime you're unable to see it during `rebuild`.

**Comment by lu4** [comment]
ok, lemme push that into new branch, it takes too long...

**Comment by vweevers** [comment]
I see, you're testing it in another project? I recommend just doing `npm run rebuild && npm t` in this `rocksdb` repo; test it in isolation.

**Comment by lu4** [comment]
Here is the MR: https://github.com/Level/rocksdb/pull/143

**Comment by lu4** [comment]
For greater verbosity I've commented out the files excluded from build, plus I moved the `port` files and added `build_version.cc` in the end of rocksdb.gyp

**Comment by lu4** [comment]
@vweevers ok, as per https://github.com/facebook/rocksdb/search?q=ods&unscoped_q=ods it turns out that I've included some strange ODS piece of code that has some relation to RocksDB stats. It probably shouldn't be included into production build. Investigating for potential reasons...

**Comment by MeirionHughes** [comment]
Its a shame this stalled - I was just looking at rockdb and it turns out they enabled 1 primary write + secondary read process support, in a newer version. 

Was there something drastic that killed this PR?

**Comment by vweevers** [comment]
> 1 primary write + secondary read process support

Sweet!

> Was there something drastic that killed this PR?

We just need someone to pick up the work. We can start by reviewing this PR, merging it, then continuing with the tasks listed here: https://github.com/Level/rocksdb/pull/141#issuecomment-533885344

**Comment by vweevers** [comment]
I updated this to RocksDB 6.17.3, fixed the few remaining issues, and squashed the commits. Thank you @filoozom @lu4!

**Comment by MeirionHughes** [comment]
tested local clone with `yarn link` and `yarn link rocksdb` and it hasn't broken my work's app. my electron rebuild fails - but I suspect that is because I'm in a mono repo and it cannot find a relative path to node-gyp while using the link.

**Comment by vweevers** [comment]
FWIW, rebuilding for Electron should not be needed because the N-API builds are runtime agnostic (unless you have an old electron version.

**Comment by MeirionHughes** [comment]
This will need a major version bump and a warning - its fine with an old database, but that auto-updated database won't be compatible with an older version of rocksdb. maybe due to https://rocksdb.org/blog/2019/03/08/format-version-4.html ?

**Comment by vweevers** [comment]
Yea, I picked this PR up because I was planning to release a major anyway for https://github.com/Level/community/issues/98.

Will add a note to our `UPGRADING.md` with a link to their `HISTORY.md`. I think the breaking version is [6.9.0](https://github.com/facebook/rocksdb/blob/master/HISTORY.md#690-03292020):

> Updated default format_version in BlockBasedTableOptions from 2 to 4. SST files generated with the new default can be read by RocksDB versions 5.16 and newer, and use more efficient encoding of keys in index blocks.

**Comment by vweevers** [comment]
[5.0.0](https://github.com/Level/rocksdb/releases/tag/v5.0.0)

**Pull request merged**
