### PR TITLE
WIP: windows support

### PR DESCRIPTION
**Pull request by mcollina**
This is building but crashing badly with no output (segfault?) when running tests. In order to make it build I had to disable the libuv port, so I fear that would be the problem.

What's the exact scope of that?

Some code might be lifted from https://github.com/chjj/rocksdown/tree/master/deps/rocksdb/port-libuv.

@vweevers would you mind to have a look?

### CODE REVIEW

**Comment by vweevers** [comment]
Because of the dynamic cast warnings, I think we need the [/GR](https://msdn.microsoft.com/en-us/library/we6hfdy0.aspx) flag. Will look into it

**Comment by ralphtheninja** [comment]
@mcollina There seems to be some issues with building it on linux as well (on master branch). Builds fine on my machine. Looking into it.

**Comment by vweevers** [comment]
The Windows build failed because a read access violation occurs on `db.open()`, due to missing RTTI. After enabling RTTI, 944/946 tests are passing 😄 Sending a PR

**Comment by vweevers** [comment]
#4

**Comment by vweevers** [comment]
```
$ ls build/Release -l
total 699256
-rw-r--r-- 1 vweevers 197121 645000452 May 31 23:56 leveldb.lib
-rw-r--r-- 1 vweevers 197121       717 May 31 23:56 leveldown.exp
-rw-r--r-- 1 vweevers 197121      1746 May 31 23:56 leveldown.lib
-rw-r--r-- 1 vweevers 197121  19756451 May 31 23:58 leveldown.map
-rwxr-xr-x 1 vweevers 197121   3995136 May 31 23:58 leveldown.node
-rw-r--r-- 1 vweevers 197121  45748224 May 31 23:58 leveldown.pdb
drwxr-xr-x 1 vweevers 197121         0 May 31 23:56 obj
-rw-r--r-- 1 vweevers 197121   1519988 May 31 23:56 snappy.lib
```

That can't be right... `leveldb.lib` is 615 MB?

**Comment by mcollina** [comment]
That does not look right. I'll have a look.

**Comment by mcollina** [comment]
@vweevers I just checked on my box, and the prebuilt comes at around 1MB gzipped.

**Comment by vweevers** [comment]
I wonder what's different on my machine, but if the appveyor prebuilts don't have the same problem, shrug.

**Comment by mcollina** [comment]
The build/ folder things are as big as yours here. But the tar.gz created by prebuild is small. I think it's due to symbols and being a debug build.

**Comment by vweevers** [comment]
Alright. I was under the assumption that prebuild tarballs the entire build folder. Guess not :)

**Comment by mcollina** [comment]
Let me check again.

**Comment by mcollina** [comment]
The prebuilt stuff is small and neat.

**Pull request merged**
