### PR TITLE
Add db.getMany(keys)

### PR DESCRIPTION
**Pull request by MeirionHughes**
#183

@vweevers I've never actually cherry picked (in like 15 years) - this seemed to have no issues being picked and applied. So you want them all in one, or one PR at a time?

### CODE REVIEW

**Comment by vweevers** [comment]
Did you have any conflicts when cherry-picking?

**Comment by vweevers** [comment]
> once I realised I needed b4085f0, there was nothing nasty

Good catch.

**Comment by vweevers** [comment]
They're cross-repo references, so for them to be auto-linked by GitHub, commits require the format `Level/leveldown@xxx`, PRs require the format `Level/leveldown#123` and yeah, HTTP URLs are good too.

**Comment by MeirionHughes** [comment]
> You might like git's interactive rebase, allows you to edit commit messages (and more) on the same branch.

hu... I didn't know you could do that. It shows up on tortoise git if I try to rebase the branch to an earlier point and select Force Rebase. 

Well they should all have links now. hopefully...

**Comment by vweevers** [comment]
[5.2.0](https://github.com/Level/rocksdb/releases/tag/v5.2.0)

**Pull request merged**
