### PR TITLE
Fix nan deprecation warnings

### PR DESCRIPTION
**Pull request by ralphtheninja**
Closes https://github.com/Level/rocksdb/issues/49

Related issue from `leveldown` https://github.com/Level/leveldown/pull/452

Squash when ready.

### CODE REVIEW

**Comment by vweevers** [comment]
@ralphtheninja you're sure this didn't need review?

**Comment by ralphtheninja** [comment]
I messed up while rebasing it. Will make a new PR.

**Comment by ralphtheninja** [comment]
@vweevers Gah. Now I noticed the standard branch pulled in the c++ changes. *sighs*

**Comment by ralphtheninja** [comment]
I can do a `git reflog` dance and re-construct a new `standard` PR without the c++ changes.

**Comment by vweevers** [comment]
I don't know reflog or what it does, will it mean a force push to master?

**Comment by ralphtheninja** [comment]
> will it mean a force push to master?

Yes it will.

**Comment by ralphtheninja** [comment]
`git reflog` doesn't do anything, it just allows you to move to non gc-ed commits, but I didn't need it this time.

`master` now contains the changes from `standard`, without the c++ changes.

**Comment by vweevers** [comment]
I would have rather seen a second commit to revert. Force pushes to master should be avoided.

**Comment by ralphtheninja** [comment]
> I would have rather seen a second commit to revert. Force pushes to master should be avoided.

I agree. I decided to do it because this time it was just a matter of minutes. Won't happen again.

**Comment by vweevers** [comment]
All good ❤️

**Pull request closed without merging**
