### PR TITLE
Rewrite to N-API

### LINKED ISSUE #100: Rewrite to N-API
- [x] Copy `binding.cc`, `binding.js`, `leveldown.js`, `chained-batch.js` and `iterator.js` from `leveldown`
- [x] Restore windows destroy patch
- [x] Change includes and add namespace alias
- [x] Add RocksDB specifics (see diff below)
  - [x] `rocksdb::Options`
  - [x] `readOnly` option
  - [x] `CompactRangeOptions`
  - [x] `blockCache` ~~(shared pointer and no delete)~~
- [x] Copy tests from `leveldown` then restore RocksDB-specifics
- [x] Copy prebuild setup from `leveldown` (without cross-compilation)
- [x] Update minimum node version and related docs
- [x] Ensure `prebuilds/` is included in npm package
- [x] Run `leak-tester-batch.js`, `leak-tester-iterator.js`, `leak-tester.js`
- [x] Add GitHub tokens

### PR DESCRIPTION
**Pull request by vweevers**
Closes #100. Though this looks like a big PR, there's not much code to review because I copied large parts from `leveldown`. That includes [`binding.cc`](https://github.com/Level/rocksdb/blob/napi/binding.cc) and all JS files including tests (`rocksdb` has only one test of its own: [`open-read-only-test.js`](https://github.com/Level/rocksdb/blob/napi/test/open-read-only-test.js)). The differences between `leveldown` and `rocksdb` are recorded in 34335413f7e6884fa3f936512c020160d85e37a5, 7a5547b585d4e9bb595be6eefbbda929b13bced7 and bcdd3170b5038474f97be0eaded28fd9a738cfa7.

### Prebuilds

Like `leveldown`, `rocksdb` now uses [`prebuildify`](https://github.com/prebuild/prebuildify) which means prebuilds will be included in the npm package. Unlike `leveldown`, `rocksdb` does not make prebuilds for ARM, Android or Alpine (until someone requests them, I figured) (and on RPi and mobile you're better off with [RocksDBLite](https://github.com/facebook/rocksdb/blob/master/ROCKSDB_LITE.md)). After initial review of this PR I'll trigger CI to make prebuilds, so we can check what the total npm package size will be.

### Additional changes

- Disable block cache if `cacheSize` is `0`, rather than using a block cache with RocksDB's default size
- Set `verify_checksums` to false (same as `leveldown` / LevelDB) (https://github.com/Level/leveldown/issues/172#issuecomment-493738959)
- Enable bloom filter (same as `leveldown` / LevelDB)
- Increase `info_log_level` from `INFO_LEVEL` to `WARN_LEVEL`

### Performance

The leak tests (`node --expose-gc test/leak-tester[-batch]`) show memory growth but I get the same results on `master` (I used node 10.14.1 on both) so it might be a preexisting leak or natural RocksDB growth.

I want to run benchmarks as well; perhaps by extracting the benchmarks from `leveldown` into a standalone tool that can target any `abstract-leveldown` implementation.

### CODE REVIEW

**Comment by vweevers** [comment]
@ralphtheninja I'm thinking we should add `--tag-libc` to the `prebuildify` command here. That way, installing `rocksdb` on Alpine will always compile (without needing `--build-from-source`) and prevent segfaults from a mismatching prebuild.

**Comment by ralphtheninja** [comment]
> @ralphtheninja I'm thinking we should add --tag-libc to the prebuildify command here. That way, installing rocksdb on Alpine will always compile (without needing --build-from-source) and prevent segfaults from a mismatching prebuild.

Sounds good!

**Comment by vweevers** [comment]
Working on the benchmarks now. Somewhat ambitious (I'll reduce the scope if it takes too much time), it's gonna use `level-test` to make isolated db's, and support any `abstract-leveldown` implementation (but node-only for now) (optionally wrapped with `encoding-down` and `levelup`) as well as `levelup`-like interfaces. It means you could compare branches:

```
git checkout master && npm i
level-bench run write --out master.csv

git checkout napi && npm i
level-bench run write --out napi.csv
```

Or implementations:

```
level-bench run write leveldown --out leveldown.csv
level-bench run write rocksdb --out rocksdb.csv
```

Or check the overhead of `encoding-down`:

```
level-bench run write memdown --transient --out baseline.csv
level-bench run write memdown --transient --encode --out encode.csv
```

Or a specific encoding:

```
level-bench run write level --db [--valueEncoding utf8] --out utf8.csv
level-bench run write level --db [--valueEncoding json] --out json.csv
```

Or compare the effect of options:

```
level-bench run write leveldown --out compressed.csv
level-bench run write leveldown --db [ --no-compression ] --out uncompressed.csv
```

Then plot runs with:

```
level-bench plot write *.csv
```

**Comment by vweevers** [comment]
Source code alone, package size is 1.8 MB, 8.5 MB unpacked. With prebuilds, the package size is 5.9 MB, 19.5 MB unpacked.

```
npm notice 3.5MB   prebuilds/darwin-x64/node.napi.glibc.node
npm notice 3.5MB   prebuilds/linux-x64/node.napi.glibc.node
npm notice 3.9MB   prebuilds/win32-x64/node.napi.glibc.node
```

(side note: I should probably remove the libc tag from the windows prebuild) (no harm, just looks weird)

**Comment by vweevers** [comment]
(first test of benchmark code, conditions may not have been optimal)

bench-20190522-22 42 15

**Comment by vweevers** [comment]
Interesting: this branch of `rocksdb` is faster (on writes) than `master`, which is slower than `leveldown`:

test

I'll try to finish those benchmarks over the weekend so y'all can play too 😄

**Comment by vweevers** [comment]
**Benchmark code available [here](https://github.com/Level/bench) (not published to npm yet, do `npm i Level/bench`).**

With some npm magic you can install `rocksdb@3` and this `napi` branch side-by-side and compare their performance. Requires npm >= 6.9.0 (for aliases) but also node < 12 (for `rocksdb@3`). If you can't upgrade npm then use `npx npm@latest`:

```
mkdir tmp && cd tmp

npx npm@latest i rocksdb3@npm:rocksdb@3 Level/rocksdb#napi --no-save
npm i Level/bench -g

level-bench run write rocksdb3
level-bench run write rocksdb
level-bench plot write
```

Repeat the last 3 steps for the other benchmarks (`write-random` and `write-sorted`). You may need to reduce the amount of data for these benchmarks (`gnuplot` crashed on me). You can do so with `-b [-n 1e6]`, for example:

```
level-bench run write-sorted rocksdb3 -b [-n 1e6]
level-bench run write-sorted rocksdb -b [-n 1e6]
level-bench plot write-sorted
```

Last note: you don't have to npm-install `rocksdb`, you can also clone the repo, install as usual, and run `level-bench run <benchmark>` (without further arguments) in that working directory.

**Results on Windows (TLDR: we're good, though we don't have read benchmarks yet):**

write
write-random
write-sorted

**Comment by vweevers** [comment]
More benchmarks are welcome, post results here! In the mean time I'm merging this.

**Pull request merged**
