### PR TITLE
Upgrade snappy to 1.1.7

### PR DESCRIPTION
**Pull request by filoozom**
Changes: https://github.com/google/snappy/blob/master/NEWS. Also fixes #78.

### CODE REVIEW

**Comment by filoozom** [comment]
Ping @ralphtheninja because of https://github.com/Level/rocksdb/pull/78#issuecomment-432323791, sorry if that's not ok.

**Comment by peakji** [comment]
LGTM!

**Comment by ralphtheninja** [comment]
wow, a tonne of code gone, nice

**Comment by ralphtheninja** [comment]
@filoozom Btw recruitment time, would you like to be invited to the level org? :smile:

**Comment by filoozom** [comment]
@ralphtheninja Well, I might be working a tiny bit on upgrading the RocksDB dependency a bit, but probably won't have a ton of time to be very active. I guess it all depends on what you expect from your members. 😄

I also worked on a new Travis configuration file to prebuild `musl` versions of this library in addition to the `glibc` ones, and started working on ARM builds but I can't get them to cross build.

**Comment by ralphtheninja** [comment]
> @ralphtheninja Well, I might be working a tiny bit on upgrading the RocksDB dependency a bit, but probably won't have a ton of time to be very active. I guess it all depends on what you expect from your members.

That's totally fine. Most members aren't that active, so no pressure at all.

**Comment by filoozom** [comment]
Well, count me in then!

**Comment by ralphtheninja** [comment]
@filoozom We could use the help in updating snappy for `leveldown` as well.

**Comment by filoozom** [comment]
It's basically a bug fix for `musl` to be honest. Nothing changed, no feature added, no speed changes, a patch should be just fine. It was even a patch for `snappy`.

**Comment by vweevers** [comment]
Does snappy follow semver?

**Comment by vweevers** [comment]
> I vote ~~minor~~, _just_ changed my mind to _patch_ :wink: 

Patch it is! I defer to your judgement on this :)

**Comment by ralphtheninja** [comment]
3.0.2

**Pull request merged**
